project_name: dotfiles
before:
  hooks:
    - go mod download
builds:
  - id: dotfiles
    env:
      - CGO_ENABLED=0
    main: ./cmd
    binary: dotfiles
    flags:
      - -trimpath
    ldflags: "-s -w -X {{.Env.BUILDMETA}}.Commit={{.ShortCommit}} -X {{.Env.BUILDMETA}}.Date={{.Date}} -X {{.Env.BUILDMETA}}.Version={{.Version}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - dotfiles

nfpms:
  - builds:
      - dotfiles
    vendor: avakarev
    homepage: "https://github.com/avakarev/dotfiles-cli"
    maintainer: "Andrii Vakarev"
    description: "CLI utility to manage dotfiles symlinks"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

# brews:
  # - goarm: 6
    # tap:
      # owner: avakarev
      # name: homebrew-tap
    # commit_author:
      # name: "Andrii Vakarev"
      # email: "avakarev@gmail.com"
    # homepage: "https://github.com/avakarev/homebrew-tap"
    # description: "CLI utility to manage dotfiles symlinks"
    # license: "MIT"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
