name: Go CI Workflow
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Lint & Test
      run: make setup-ci ci
    - uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true
        version: latest
    - name: Dry run release
      run: make release-dryrun
